version: '3'
services:
  minerva:
    build: ./
    tty: true # gives colorized logs in docker-compose logs
    entrypoint: 'npm start'
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  hoster:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

volumes:
  mongo_data:
